### ISSUE TITLE
Make <datalist> compatible with Safari and IE

### ISSUE THREAD

**Issue by jessicasalmon** [FAC10/week4-jajascript#21]
If we use the <datalist> element, our autocomplete will not work on safari and IE (13% of global usage). See http://caniuse.com/#feat=datalist

Some promising solutions appear to be:
*   [vanilla JS a polyfill, looks the better option as it mimics the behaviour of datalist](https://github.com/Fyrd/purejs-datalist-polyfill)
* [workaround which will show users of safari/IE a <select> dropdown with the options](http://www.devcurry.com/2011/08/html-5-datalist-element-with-fallback.html)

**Comment by joeylouise** [comment]
Instead of using datalist, we are using an `ul` element and appending `li`s
- This overcomes the compatibility issue and allows us to link to google search easily within `li`s
