### ISSUE TITLE
Autocomplete not working :(

### ISSUE THREAD

**Issue by msachi** [FAC10/week4-jajascript#64]
I've tried both the local and the deployed version, in both cases the server hangs and eventually logs an error in the console. Does it work on your computers?

<img width="558" alt="screen shot 2017-03-17 at 10 21 19" src="https://cloud.githubusercontent.com/assets/17763838/24038995/924fdb08-0afb-11e7-8239-0d7fad815458.png">

**Comment by msachi** [comment]
Ok, I see that you're not actually sending a response back to the front-end

**Comment by jessicasalmon** [comment]
We were sad about this too, but we fixed it :) We weren't parsing or stringifying our array before we (tried to) send the response back to the front-end
